#登陆相关配置
login:
  #开放的模拟登陆api服务器地址 
  api: "http://www.zimo.wiki:8080/wisedu-unified-login-api-v1.0/api/login"

#今日校园相关配置
cpdaily:
  #表单组默认选项配置
  defaults:
    - default:
        title: 今天体温是否正常
        type: 2
        value: 体温正常（<37.3℃）
    - default:
        title: 今天是否去过中高风险地区
        type: 2
        value: 否
    - default:
        title: 今天是否有跨市域移动
        type: 2
        value: 否
    - default:
        title: 今日状态
        type: 2
        value: 正常
